apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: cluster-teste-otlp-template-2-location
  description: Location to import all cluster-teste-otlp-template-2 catalog components
spec:
  targets:
    - ./.platform/*.yaml
